name: Doc Search Scripts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'doc-search'

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Run scripts
        run: |
          cd docsearch
          echo "APPLICATION_ID=${{ secrets.GATSBY_ALGOLIA_APPLICATION_ID }}\nAPI_KEY=${{ secrets.GATSBY_ALGOLIA_API_KEY }}\nGITHUB_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}" > .env
          export DOCKER_REGISTRY="${{ secrets.DOCKER_REGISTRY }}"
          ./run-algolia-crawler-incrementally.sh .
      - name: Run scripts
        run: |
          cd docsearch
          touch .env
          echo "APPLICATION_ID=${{ secrets.GATSBY_ALGOLIA_APPLICATION_ID }}" >> .env
          echo "API_KEY=${{ secrets.GATSBY_ALGOLIA_API_KEY }}" >> .env
          echo "GITHUB_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}" >> .env
          export DOCKER_REGISTRY="${{ secrets.DOCKER_REGISTRY }}"
          export GITHUB_AUTH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
          ./run-algolia-crawler-incrementally.sh `pwd`
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update latest_commit.json"
          git push
